### ISSUE TITLE
`TEST`: Run mutation tests only in dev branch

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1640]
### Is your feature request related to a problem? Please describe.

Currently, mutation tests are being executed for all dev and test branches. This can slow down the CI process and is unnecessary for non-dev branches. We'd like to limit the mutation tests to only run on the dev branch.

### Describe the solution you'd like

Playwright can be configured to run specific tests or skip certain ones based on the branch or environment by customizing your CI configuration. While Playwright itself doesn't handle branches directly, GitHub Actions can be configured to handle this.

Here’s how you can achieve this:

Use environment variables: Set up an environment variable in your CI for the branch name. Then, in your Playwright test configuration, you can conditionally skip certain tests if the branch is not dev.

GitHub Actions (or other CI tools): Modify your CI workflow to only run mutation tests on the dev branch. For example, in GitHub Actions, you can specify branches in the workflow YAML file to trigger specific jobs only on certain branches.

```yaml
name: Playwright Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Unit & Integration Tests
        run: npm run test

  mutation-test:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Mutation Tests
        run: npm run mutation-test
```

### Example Playwright test configuration (using environment variables):

```ts
import { test } from '@playwright/test';

test.describe('Mutation tests', () => {
  test('Run mutation tests conditionally', async ({ page }) => {
    if (process.env.CI_BRANCH !== 'dev') {
      test.skip('Skipping mutation tests on non-dev branches');
    }
    // Your mutation test logic here
  });
});
```
