### ISSUE TITLE
FEAT: Run Tests Only for Changed Files on Specific Branches

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1870]
### Description:

Implement a mechanism to run tests only for changed/updated files if the branch name starts with `test/` or `/onboarding`.

#### Steps to Implement:

- **Identify Changed Files:** Use Git to list the changed files.
- **Filter Test Files:** Extract test files from the list of changed files.
- **Run Tests:** Use Playwright to run tests for the filtered files.
- **CI/CD Configuration:** Configure the CI/CD pipeline to detect branches and execute the tests conditionally.

**Comment by 7alip** [comment]
### 1. Run Tests Only for Changed/Updated Files Using Playwright

You can achieve this by using a combination of Playwright and Git commands. Here's a general approach:

- **Step 1**: Identify the changed files using Git.
  ```bash
  git diff --name-only HEAD~1
  ```

- **Step 2**: Filter the test files from the list of changed files.
  
- **Step 3**: Run Playwright tests for those files.
  ```javascript
  const { execSync } = require('child_process');
  const { test, expect } = require('@playwright/test');

  const changedFiles = execSync('git diff --name-only HEAD~1').toString().split('\n');
  const testFiles = changedFiles.filter(file => file.includes('.spec.ts'));

  testFiles.forEach(file => {
    test(file, async ({ page }) => {
      // Your test logic here
    });
  });
  ```

### 2. Detect Branches Starting with `test/` or `/onboarding` in the CI/CD Pipeline

You can configure your CI/CD pipeline (e.g., GitHub Actions) to check the branch name and run the tests accordingly.

- **GitHub Actions Configuration**:
  ```yaml
  name: Run Tests

  on:
    push:
      branches:
        - 'test/*'
        - '/onboarding/*'
      
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run tests
          run: |
            git diff --name-only HEAD~1 > changed_files.txt
            changed_files=$(cat changed_files.txt | grep '.spec.ts')
            if [ -n "$changed_files" ]; then
              npx playwright test $changed_files
            else
              echo "No test files changed"
            fi
  ```

1. **Identify Changed Files**: Use Git commands to list the changed files.
2. **Filter Test Files**: Extract the test files from the list of changed files.
3. **Run Tests Conditionally**: Configure the CI/CD pipeline to run the tests based on branch names.
